In [1]:
import pandas as pd
import pandera as pa
from datetime import date, time, datetime, timedelta

In [2]:
valores_ausentes = ['**','####','###!','****','*****','NULL','***']
df = pd.read_csv("ocorrencia.csv", 
                 sep = ";", 
                 parse_dates = ['ocorrencia_dia'], 
                 dayfirst = True, 
                 na_values = valores_ausentes )
#na_values poderia ser usado como -> df.replace(['**','####','###!','****','*****','NULL'], pd.NA, inplace = True)
df.drop(['codigo_ocorrencia1',
         'codigo_ocorrencia3',
         'codigo_ocorrencia4',
         'ocorrencia_latitude',
         'ocorrencia_longitude',
         'codigo_ocorrencia2',
         'ocorrencia_pais',
         'investigacao_aeronave_liberada',
         'investigacao_status',
         'divulgacao_relatorio_numero',
         'divulgacao_relatorio_publicado',
         'divulgacao_dia_publicacao',
         "ocorrencia_hora",
         'total_aeronaves_envolvidas',
         'ocorrencia_saida_pista'], inplace=True, axis=1)
df.drop_duplicates(inplace=True)

In [3]:
schema = pa.DataFrameSchema(
        columns = {
            "Não_necessária":pa.Column(pa.Int, required = False),     
            "ocorrencia_classificacao":pa.Column(pa.String),
            "ocorrencia_cidade":pa.Column(pa.String),
            "ocorrencia_uf":pa.Column(pa.String, pa.Check.str_length(2,2), nullable = True),
            "ocorrencia_aerodromo":pa.Column(pa.String, nullable = True),
            "codigo_ocorrencia":pa.Column(pa.Int),
            "ocorrencia_dia":pa.Column(pa.DateTime),
            "total_recomendacoes":pa.Column(pa.Int),
        }
)

In [4]:
schema.validate(df)

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,total_recomendacoes
0,52242,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-05,0
1,45331,ACIDENTE,GUARULHOS,SP,SBGR,2012-01-06,3
2,45333,ACIDENTE,VIAMÃO,RS,NaN,2012-01-06,0
3,45401,ACIDENTE,SÃO SEBASTIÃO,SP,NaN,2012-01-06,0
4,45407,ACIDENTE,SÃO SEPÉ,RS,NaN,2012-01-06,0
...,...,...,...,...,...,...,...
5162,80458,ACIDENTE,JATAÍ,GO,NaN,2021-12-30,0
5163,80452,ACIDENTE,MARACAÍ,SP,NaN,2021-12-31,0
5164,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,SSNH,2021-12-31,0
5165,80460,INCIDENTE,CURITIBA,PR,SBBI,2021-12-31,0
5166,80467,INCIDENTE,PETROLINA,PE,SBPL,2021-12-31,0

In [5]:
if(df.codigo_ocorrencia.is_unique):
    df.set_index('codigo_ocorrencia', inplace = True)

In [6]:
data_atual = datetime.now()
data_atual_str = data_atual.strftime('%d-%m-%Y_%H:%M:%S')
df.to_excel('/home/ltk/DEV/BootCamp-Python/Data_engineer/Jupyter/{}.xlsx'.format(data_atual_str))